engines:
  fixme:
    enabled: true
  pmd:
    enabled: true
    config: pmd-ruleset.xml
    channel: "beta"
  checkstyle:
    enabled: true
    config: checkstyle.xml
    channel: "beta"
ratings:
  paths: "**.java"
