language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

services:
  - docker

script: mvn test -P securityAndLicenseCheck

after_success:
  - mvn jacoco:report coveralls:report docker:build
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=mcpringle/moodini
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker tag -f $REPO:$COMMIT $REPO:$TAG
  - docker tag -f $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
  - docker logout

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b2b7ada590d98c53b19c
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always    # options: [always|never|change] default: always

cache:
  directories:
  - .autoconf
  - $HOME/.m2