language: java

jdk:
  - oraclejdk8

services:
  - docker

addons:
  apt:
    packages:
      - oracle-java8-installer

after_success:
  - docker build -t mcpringle/moodini .
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push mcpringle/moodini
  - docker logout

env:
  global:
  - secure: f+rmwtpOD+vdRsjeLG1REGvTG1NMnw94jow00i7sI74+d7wCgxwLT4OyHOQ7nVmHbALS2Um9NxltzV8GsGTbkDOuUbhNR379578inOGWJDdqoz7ROK7ucBoPfCM++sfjL1zwj9gB8XzVObNkYpfSZr6jWCz/18IhLg9gu0WnV1XE+YDyRbKyksJwC0OYAq+9ZSrm0y5HKMB115wVTfSlPwNwRCZFd9vaqYBGKt2Lmi7iVIW5Zmp8QXubSHR5fqueayRENQZJMwvV+sXe33I69F2pJLkERLzn5L6cCPRJXOgFq6VHvjKEWQ8h6TGjJ2iCLNH7ZPDEqz6xoADrMHUMYR8tWLKXaWG5jOAsNt4FMCjKa0V7WkLv9+utoxKmpdVemaknWx3vBnw2ujQaO3d+AMXJY4nwGtk28iwRFqBYDPs2DwD35uH1WL4TSJPq+oaoGbiG+ACqfUXcz9fg3ZgMnh0Pd759CuT3PcW79Wn4qsEGts9TQ47GH+FPswDQoKjS3xmghA6Hh1FpZA6rhGk5DI9yKpONjxhfeVvlfC9JAUcTdCiBAqnUVcuvXc1kPRVWxY17+z6J8ax1ttskWm9svnzdYuRqglbP5A3NIiHwf6OujmGRW1z7IiEtWp0gFMkwIVRcH49hW+/+Gp3IMQPIfGZNGvgcB/VroUbaykN9N+Y=
  - secure: OpIrSXLd1W9JbaRB/dKoTCcNltPrp6avRCQIhOaFzbsaqzsuIKVwtgmj1Y7zdPphaCtYGkGln68BkGQYGx98zWyUoEq3hQrtdxh/u+g75UazDpKX8g5DvJ6EQLEYfWbpHSbydetY8YBXtXjVEqrAstJMqQ2aAGFFaBYrmRMRasdlVb0o8sI+MxEzRaFt59TARiWcAfbFCFav63Ai8OH+9Mbbeb9Va/PoLt31aT26Z1p2vtzCzMNUyISsULcP2xwOY1hi4/RPprro6k6ytVUGsuBJkkdobnQqpW0H6pAcGTql6SMyiFM8ijWhZupnjnTjPgtTfyHLkFtt2FY/uLPzq1HSYz1NeWWQ+xihUe6wIxys900ky2HtQq60peoU19zzURkMxQP2ur/jBfbaqCBZ65zP8LNNSEpBj4LQ1afd8Y4B6AnmwV6IsiPPotk+jzazTg+HSIv7d6mCdIlvugISHpsO+16CPl8cnbYEjvhY0MOPbVEMUf2w8ynsgZs5Z1QpHU+rWcG0kNPyoqNHH+Lp1XG7MWWaRBkEGYjmYNbNyrRnR8Ap2NSNjiENb4IN1rd3BJQrusU9mvZj8mFaaXUe9oh4K2qj7kRlhhNy5p5HUeIg3DbL1O17VX2SlLwcNyz7BB25NSZ9dtDJb1Qgt9GOaD2r2WQWfz5fei4/mAIETDI=
  - secure: LxIIOZwlEiwfUnlmTO7G7EjaI7Y8//VnAZRvANEaFHJYJgI6Qo04cJU5mBDQX6IKjhkSbKr0oeazEG6uEoHn6mDe864rhs0e6FR7KqUYW2jyUaSoMB8dAMdRPnVToH+Zjfe1qsXiKxc4ZCAaynp+gvYiEvrrIHfg02/c1IdANcqxUtDIhtRQBHChU2dHdMHBe/r6C2rr6RQuiAfGd9nAs7fYAVlFmb0y5/olTr4txUCw7YJ3xwOzemOgLdUf93aKeV+iw3iRQS3UNMK3os2Ta0Uh3i86ZCFRpxWA+U1stT4XsFkpzECQKOiN/MtX0Z73aqOsioJebms3g7H/DROJPY9zeEN+yAN0Y3nEvVojCCJfDHfqJgh/TFjg5Pp9nA4Xjnym2cNbhE2Zca7UrIEy9267qIHibECzAmdHV+1mJbXGKuqGNktOCfFURNjqpBJhrWIjTv3lQkDAYFyz06VFMxEsUDFtmvepuxDj/4EbkZiVfXRuep8qmzGLgDdqu9hHgK6AWFyjKNmicn40xgLjChPeA8M1dqcj3TvCqwAqqKNmXLtoxDBmHSlRwpkCG3yuvmOQ9nNNxc/Sry8y5jacCCb5xyr7GB+yZKI55WAuPRYRtOiA3EjKuTi0UBL7CvBk4/Hr3Y/nyzEIO838dYxbt27BBDcTE1Y6prNLuqlzmmo=

script:
  - ./gradlew check jacocoTestReport coveralls sonarqube -Dsonar.login=$SONAR_TOKEN
