#!/bin/bash

export DISPLAY=:99.0

set -ex

# init key for pass
gpg --batch --gen-key <<-EOF
%echo Generating a standard key
Key-Type: DSA
Key-Length: 1024
Subkey-Type: ELG-E
Subkey-Length: 1024
Name-Real: Travis Moodini
Name-Email: travis@moodini.ch
Expire-Date: 0
# Do a commit here, so that we can later print "done" :-)
%commit
%echo done
EOF

key=$(gpg --no-auto-check-trustdb --list-secret-keys | grep ^sec | cut -d/ -f2 | cut -d" " -f1)
pass init $key

echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
docker push mcpringle/moodini
docker logout
